# Generated by Django 5.0.2 on 2024-03-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=100, unique=True)),
                ('dept', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='data',
        ),
    ]
