# Generated by Django 5.0.2 on 2024-03-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelog', '0002_registered_delete_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='img',
            field=models.FileField(default=None, max_length=250, upload_to='file/'),
        ),
    ]
