# Generated by Django 5.0.2 on 2024-03-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelog', '0008_remove_registered_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='img',
            field=models.FileField(default=None, max_length=250, upload_to='file/'),
        ),
    ]
