# Generated by Django 5.0.2 on 2024-03-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelog', '0009_registered_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered',
            name='img',
        ),
    ]
